language: python
cache:
    directories:
        - .tox

python: 2.7
env:
    - TOX_ENV=py27
    - TOX_ENV=docs
    - TOX_ENV=flake8
install:
    - pip install -e .
    - pip install -r requirements.txt
    - pip install tox

# command to run tests
script:
    - tox -e $TOX_ENV
    - py.test
